# Generated by Django 5.2.1 on 2025-05-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='机场名称')),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ICAO代码')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_owner', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否本企业机场')),
                ('is_air_harbor', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否水上机场')),
                ('is_temporary', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否临时站点')),
                ('is_tower', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否塔台机场')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(choices=[(False, '未删除'), (True, '已删除')], default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机场',
                'verbose_name_plural': '机场',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=10, unique=True, verbose_name='员工编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('nationality', models.CharField(max_length=10, verbose_name='国籍')),
                ('ID_type', models.CharField(blank=True, max_length=10, verbose_name='证件类型')),
                ('ID_number', models.CharField(blank=True, max_length=20, verbose_name='证件号')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('nation', models.CharField(blank=True, max_length=100, verbose_name='民族')),
                ('native_place', models.CharField(blank=True, max_length=100, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='通讯地址')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('political_status', models.CharField(blank=True, max_length=10, verbose_name='政治面貌')),
                ('marital_status', models.SmallIntegerField(blank=True, choices=[(1, '已婚'), (2, '未婚'), (3, '离异'), (4, '丧偶')], null=True, verbose_name='婚姻状况')),
                ('education_level', models.SmallIntegerField(blank=True, choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '大专'), (5, '本科'), (6, '硕士'), (7, '博士')], null=True, verbose_name='教育程度')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='紧急联系人姓名')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系人电话')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, verbose_name='紧急联系人关系')),
                ('employment_type', models.SmallIntegerField(choices=[(1, '全职'), (2, '兼职'), (3, '实习'), (4, '临时')], default=1, verbose_name='入职类型')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('confirmable_date', models.DateField(blank=True, null=True, verbose_name='转正日期')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('is_coach', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否教员')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('is_deleted', models.BooleanField(choices=[(False, '未删除'), (True, '已删除')], default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='OperatingBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('base_type', models.SmallIntegerField(blank=True, choices=[(1, '主运行基地'), (2, '辅助运行基地')], null=True, verbose_name='基地类型')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(choices=[(False, '未删除'), (True, '已删除')], default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.employee', verbose_name='负责人')),
                ('ope_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.airport', verbose_name='运行机场')),
            ],
            options={
                'verbose_name': '运行基地',
                'verbose_name_plural': '运行基地',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='ope_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.operatingbase', verbose_name='所属基地'),
        ),
    ]
