# Generated by Django 5.2.1 on 2025-06-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='is_air_harbor',
            field=models.BooleanField(default=False, verbose_name='是否水上机场'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='是否本企业机场'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='是否临时站点'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_tower',
            field=models.BooleanField(default=False, verbose_name='是否塔台机场'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态'),
        ),
    ]
