# Generated by Django 5.2.1 on 2025-06-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0003_alter_airport_latitude_alter_airport_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='OperatingBase',
            old_name='ope_airport',
            new_name='airport',
        ),
    ]
