# Generated by Django 5.2.1 on 2025-06-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0005_alter_employee_is_coach_alter_employee_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='公司名称')),
                ('name_en', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='外文名称')),
                ('name_short', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='简称')),
                ('found_time', models.DateField(blank=True, null=True, verbose_name='成立时间')),
                ('legal_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='法人')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.company', verbose_name='上级公司')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.company', verbose_name='所属公司'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.company', verbose_name='所属公司')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.department', verbose_name='所属部门'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='职位名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.position', verbose_name='职位'),
        ),
    ]
