# Generated by Django 5.2.1 on 2025-06-15 05:56

import django.db.models.deletion
import fly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0006_company_employee_company_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='机型名称')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='生产厂商')),
                ('aircraft_nature', models.SmallIntegerField(choices=[(1, '单发陆地'), (2, '多发陆地')], default=1, verbose_name='机型性质')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机型',
                'verbose_name_plural': '机型',
            },
        ),
        migrations.CreateModel(
            name='FlightCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '飞行课程',
                'verbose_name_plural': '飞行课程',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('employee', '员工'), ('student', '学员')], max_length=10, verbose_name='人员类型')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('nationality', models.CharField(blank=True, max_length=10, null=True, verbose_name='国籍')),
                ('ID_type', models.CharField(blank=True, max_length=10, verbose_name='证件类型')),
                ('ID_number', models.CharField(blank=True, max_length=20, verbose_name='证件号')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('political_status', models.CharField(blank=True, max_length=10, verbose_name='政治面貌')),
                ('nation', models.CharField(blank=True, max_length=100, verbose_name='民族')),
                ('native_place', models.CharField(blank=True, max_length=100, verbose_name='籍贯')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='通讯地址')),
                ('education_level', models.SmallIntegerField(blank=True, choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '大专'), (5, '本科'), (6, '硕士'), (7, '博士')], verbose_name='教育程度')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='紧急联系人姓名')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系人电话')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, verbose_name='紧急联系人关系')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=fly.models.get_emp_photo_path, verbose_name='照片'),
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='机号')),
                ('introduction_date', models.DateField(blank=True, null=True, verbose_name='引进日期')),
                ('device_type', models.SmallIntegerField(choices=[(1, '真机'), (2, '训练器'), (3, '模拟机')], default=1, verbose_name='设备类型')),
                ('status', models.SmallIntegerField(choices=[(1, '适航'), (2, '待检'), (3, '定检中'), (4, '大修'), (5, '损伤'), (6, '损毁'), (99, '停用')], default=1, verbose_name='状态')),
                ('airworthiness_certificate', models.FileField(blank=True, null=True, upload_to=fly.models.get_aircraft_file_path, verbose_name='适航证')),
                ('radio_station_license', models.FileField(blank=True, null=True, upload_to=fly.models.get_aircraft_file_path, verbose_name='电台执照')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to=fly.models.get_aircraft_file_path, verbose_name='国籍登记证')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.company', verbose_name='所属公司')),
                ('ope_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.operatingbase', verbose_name='运行基地')),
                ('aircraft_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.aircrafttype', verbose_name='机型')),
            ],
        ),
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField(verbose_name='飞行日期')),
                ('field_transition', models.SmallIntegerField(choices=[(1, '本场'), (2, '转场')], default=1, verbose_name='本转性质')),
                ('fly_nature', models.SmallIntegerField(blank=True, choices=[(1, '带飞'), (2, '单飞'), (3, '机长'), (4, '副驾驶')], null=True, verbose_name='飞行性质')),
                ('day_night', models.SmallIntegerField(choices=[(1, '昼间'), (2, '夜间'), (3, '跨昼夜')], default=1, verbose_name='昼夜性质')),
                ('fly_category', models.SmallIntegerField(blank=True, choices=[(1, '飞行娱乐'), (2, '飞行训练'), (3, '阶段检查'), (4, '实践考试'), (5, '任教检查'), (6, '熟练检查'), (7, '单飞'), (8, '螺旋'), (99, '其他')], null=True, verbose_name='飞行种类')),
                ('open_time', models.TimeField(verbose_name='开车时间')),
                ('take_off_time', models.TimeField(blank=True, null=True, verbose_name='起飞时间')),
                ('landing_time', models.TimeField(blank=True, null=True, verbose_name='落地时间')),
                ('close_time', models.TimeField(verbose_name='关车时间')),
                ('flight_duration', models.SmallIntegerField(verbose_name='飞行时长')),
                ('flight_sortie', models.SmallIntegerField(blank=True, null=True, verbose_name='起落架次')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.aircraft', verbose_name='航空器')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.aircrafttype', verbose_name='机型')),
                ('arrival_airport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_records', to='fly.airport', verbose_name='到达机场')),
                ('departure_airport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_records', to='fly.airport', verbose_name='出发机场')),
                ('flight_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.flightcourse', verbose_name='飞行课程')),
                ('task_pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='fly.employee', verbose_name='任务飞行员')),
                ('left_seat_person', models.ManyToManyField(blank=True, related_name='left_seat_person', to='fly.person', verbose_name='左座人员')),
                ('right_seat_person', models.ManyToManyField(blank=True, related_name='right_seat_person', to='fly.person', verbose_name='右座人员')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fly.person')),
                ('stu_code', models.CharField(max_length=10, unique=True, verbose_name='学员编号')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=fly.models.get_emp_photo_path, verbose_name='照片')),
                ('student_type', models.SmallIntegerField(choices=[(1, '本校教员'), (2, '整体课程'), (3, '分体课程'), (4, '熟练检查'), (5, '商用补时'), (6, '外籍换照'), (7, '实践考试'), (99, '其他')], default=1, verbose_name='学员类型')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='入校日期')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='是否临时')),
                ('status', models.SmallIntegerField(default=1, verbose_name='学籍状态')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='毕业/退学日期')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.company', verbose_name='训练单位')),
                ('ope_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.operatingbase', verbose_name='训练基地')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
            },
            bases=('fly.person',),
        ),
    ]
