# Generated by Django 5.2.1 on 2025-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0007_aircrafttype_flightcourse_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='education_level',
            field=models.CharField(blank=True, choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '大专'), (5, '本科'), (6, '硕士'), (7, '博士')], max_length=50, verbose_name='教育程度'),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, choices=[(1, '父母'), (2, '祖父母'), (3, '兄弟姐妹'), (4, '配偶'), (5, '其他')], max_length=50, verbose_name='紧急联系人关系'),
        ),
    ]
