# Generated by Django 5.2.1 on 2025-06-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0008_alter_person_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ID_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证件号'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ID_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='通讯地址'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education_level',
            field=models.SmallIntegerField(blank=True, choices=[(1, '小学'), (2, '初中'), (3, '高中'), (4, '大专'), (5, '本科'), (6, '硕士'), (7, '博士')], null=True, verbose_name='教育程度'),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='紧急联系人姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系人电话'),
        ),
        migrations.AlterField(
            model_name='person',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, choices=[(1, '父母'), (2, '祖父母'), (3, '兄弟姐妹'), (4, '配偶'), (5, '其他')], max_length=50, null=True, verbose_name='紧急联系人关系'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='person',
            name='native_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='person',
            name='political_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='政治面貌'),
        ),
    ]
