# Generated by Django 5.2.1 on 2025-06-15 07:50

from django.db import migrations, models

def transfer_data(apps, schema_editor):
    OldEmployee = apps.get_model('fly', 'Employee')
    Person = apps.get_model('fly', 'Person')

    for emp in OldEmployee.objects.all():
        # 创建对应的Person记录
        person = Person.objects.create(
            name=emp.name,
            gender=emp.gender,
            nationality=emp.nationality,
            ID_type=emp.ID_type,
            ID_number=emp.ID_number,
            birth_date=emp.birth_date,
            nation=emp.nation,
            native_place=emp.native_place,
            address=emp.address,
            phone=emp.phone,
            email=emp.email,
            political_status=emp.political_status,
            education_level=emp.education_level,
            emergency_contact_name=emp.emergency_contact_name,
            emergency_contact_phone=emp.emergency_contact_phone,
            emergency_contact_relationship=emp.emergency_contact_relationship,
            is_deleted=emp.is_deleted,
            created_at=emp.created_at,
            updated_at=emp.updated_at,
        )
        # 更新Employee记录关联Person
        emp.person_ptr = person
        emp.save()


def disassociate_employees(apps, schema_editor):
    # 回滚操作
    Employee = apps.get_model('fly', 'Employee')
    Employee.objects.update(person_ptr=None)

class Migration(migrations.Migration):
    dependencies = [
        ('fly', '0009_alter_person_id_number_alter_person_id_type_and_more'),
    ]

    operations = [
        # 1. 添加可为空的外键
        migrations.AddField(
            model_name='employee',
            name='person_ptr',
            field=models.OneToOneField(
                on_delete=models.CASCADE,
                to='fly.Person',
                null=True,
                blank=True,
            ),
        ),

        # 2. 数据迁移（将原有Employee关联到Person）
        migrations.RunPython(
            code=transfer_data,
            reverse_code=disassociate_employees
        ),

        # 3. 移除 `id` 的主键约束（但不删除列）
        migrations.RunSQL(
            sql="ALTER TABLE fly_employee MODIFY COLUMN id INT NOT NULL;",  # 移除自增主键
            reverse_sql="ALTER TABLE fly_employee MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;",
        ),

        # 6. 移除与Person重复的字段
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ID_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ID_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='native_place',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='political_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        )
    ]
