# Generated by Django 5.2.1 on 2025-06-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0011_remove_employee_id_alter_employee_person_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcourse',
            name='aircraft_nature',
            field=models.SmallIntegerField(choices=[(1, '单发陆地'), (2, '多发陆地')], default=1, verbose_name='机型性质'),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='day_night',
            field=models.SmallIntegerField(choices=[(1, '昼间'), (2, '夜间'), (3, '跨昼夜')], default=1, verbose_name='昼夜性质'),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='device_type',
            field=models.SmallIntegerField(choices=[(1, '真机'), (2, '训练器'), (3, '模拟机')], default=1, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='field_transition',
            field=models.SmallIntegerField(choices=[(1, '本场'), (2, '转场')], default=1, verbose_name='本转性质'),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='fly_category',
            field=models.SmallIntegerField(choices=[(1, '飞行娱乐'), (2, '飞行训练'), (3, '阶段检查'), (4, '实践考试'), (5, '任教检查'), (6, '熟练检查'), (7, '单飞'), (8, '螺旋'), (99, '其他')], default=2, verbose_name='飞行种类'),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='fly_nature',
            field=models.SmallIntegerField(blank=True, choices=[(1, '带飞'), (2, '单飞'), (3, '机长'), (4, '副驾驶')], null=True, verbose_name='飞行性质'),
        ),
    ]
