# Generated by Django 5.2.1 on 2025-06-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0012_flightcourse_aircraft_nature_flightcourse_day_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrecord',
            name='arrival_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_records', to='fly.airport', verbose_name='到达机场'),
        ),
        migrations.AlterField(
            model_name='flightrecord',
            name='departure_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_records', to='fly.airport', verbose_name='出发机场'),
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='left_seat_person',
        ),
        migrations.RemoveField(
            model_name='flightrecord',
            name='right_seat_person',
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='left_seat_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_seat_person', to='fly.person', verbose_name='左座人员'),
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='right_seat_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_seat_person', to='fly.person', verbose_name='右座人员'),
        ),
    ]
