# Generated by Django 5.2.1 on 2025-06-19 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0013_alter_flightrecord_arrival_airport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightrecord',
            options={'verbose_name': '飞行记录', 'verbose_name_plural': '飞行记录'},
        ),
        migrations.AddField(
            model_name='airport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airport',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_air_harbor',
            field=models.BooleanField(default=False, verbose_name='水上机场'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='本企业机场'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='临时站点'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_tower',
            field=models.BooleanField(default=False, verbose_name='塔台机场'),
        ),
    ]
