# Generated by Django 5.2.1 on 2025-06-19 15:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fly', '0014_alter_flightrecord_options_airport_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_type_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_type_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_course_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightcourse',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_course_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_record_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_record_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatingbase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ope_base_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatingbase',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ope_base_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airport',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFlightRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('flight_date', models.DateField(verbose_name='飞行日期')),
                ('field_transition', models.SmallIntegerField(choices=[(1, '本场'), (2, '转场')], default=1, verbose_name='本转性质')),
                ('fly_nature', models.SmallIntegerField(blank=True, choices=[(1, '带飞'), (2, '单飞'), (3, '机长'), (4, '副驾驶')], null=True, verbose_name='飞行性质')),
                ('day_night', models.SmallIntegerField(choices=[(1, '昼间'), (2, '夜间'), (3, '跨昼夜')], default=1, verbose_name='昼夜性质')),
                ('fly_category', models.SmallIntegerField(blank=True, choices=[(1, '飞行娱乐'), (2, '飞行训练'), (3, '阶段检查'), (4, '实践考试'), (5, '任教检查'), (6, '熟练检查'), (7, '单飞'), (8, '螺旋'), (99, '其他')], null=True, verbose_name='飞行种类')),
                ('open_time', models.TimeField(verbose_name='开车时间')),
                ('take_off_time', models.TimeField(blank=True, null=True, verbose_name='起飞时间')),
                ('landing_time', models.TimeField(blank=True, null=True, verbose_name='落地时间')),
                ('close_time', models.TimeField(verbose_name='关车时间')),
                ('flight_duration', models.SmallIntegerField(verbose_name='飞行时长')),
                ('flight_sortie', models.SmallIntegerField(blank=True, null=True, verbose_name='起落架次')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除状态')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aircraft', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.aircraft', verbose_name='航空器')),
                ('aircraft_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.aircrafttype', verbose_name='机型')),
                ('arrival_airport', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.airport', verbose_name='到达机场')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departure_airport', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.airport', verbose_name='出发机场')),
                ('flight_course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.flightcourse', verbose_name='飞行课程')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('left_seat_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.person', verbose_name='左座人员')),
                ('right_seat_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.person', verbose_name='右座人员')),
                ('task_pilot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.employee', verbose_name='任务飞行员')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 飞行记录',
                'verbose_name_plural': 'historical 飞行记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
