# Generated by Django 5.2.1 on 2025-07-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0017_proxypermission_flightrecord_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='ope_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fly.operatingbase', verbose_name='飞行基地'),
        ),
        migrations.AddField(
            model_name='historicalflightrecord',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='historicalflightrecord',
            name='ope_base',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fly.operatingbase', verbose_name='飞行基地'),
        ),
    ]
